import React, { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
import { Loader2 } from 'lucide-react';

const PaymentMethodTabs = ({ selectedNumber }) => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);

  const handlePayment = async (e) => {
    e.preventDefault();

    if (!selectedNumber) {
      alert("No number selected");
      return;
    }

    setLoading(true);

    const payload = {
      orderId: `ORD-${Date.now()}`,
      amount: Number(selectedNumber.price),
      method: 'card',
      phoneNumber: selectedNumber.phone_number
    };

    try {
      const response = await fetch('http://localhost:5000/api/pay', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      const data = await response.json();

      if (data.success) {
        // SUCCESS: Pass the activationCode to the next page
        navigate('/payment/success', {
          state: {
            transactionId: data.transactionId,
            activationCode: data.activationCode, // <--- CRITICAL: Passing the code generated by backend
            date: new Date().toISOString(),
            method: "Visa **** 1292",
            amount: `LKR ${selectedNumber.price}`,
            phoneNumber: selectedNumber.phone_number // Changed from .number to .phone_number to match payload
          }
        });
      } else {
        alert("Payment failed. Please try again.");
      }
    } catch (error) {
      console.error("Payment error:", error);
      alert("Something went wrong during payment.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="w-full">
      <h3 className="text-lg font-semibold mb-4">
        Choose your payment method
      </h3>

      <Tabs defaultValue="card" className="w-full">
        <TabsList className="grid w-full grid-cols-2 mb-6 bg-gray-200/50 p-1">
          <TabsTrigger value="card" className="bg-white shadow-sm">
            Credit / Debit Card
          </TabsTrigger>
          <TabsTrigger value="wallet">
            Mobile Wallet
          </TabsTrigger>
        </TabsList>

        {/* CARD PAYMENT */}
        <TabsContent value="card">
          <form onSubmit={handlePayment} className="space-y-4">
            <Input placeholder="Card Number" required pattern="[0-9]{13,19}" />
            <div className="grid grid-cols-2 gap-4">
              <Input placeholder="MM/YY" required pattern="(0[1-9]|1[0-2])\/?([0-9]{2})" />
              <Input placeholder="CVC" required pattern="[0-9]{3,4}" type="password" />
            </div>
            <Input placeholder="Cardholder Name" required />

            <Button
              type="submit"
              className="w-full bg-blue-600 hover:bg-blue-700 h-11 text-base"
              disabled={loading}
            >
              {loading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Processing...
                </>
              ) : (
                "Simulate Payment"
              )}
            </Button>
          </form>
        </TabsContent>

        {/* WALLET */}
        <TabsContent value="wallet">
          <div className="p-6 text-center text-gray-500 bg-gray-50 rounded-lg border border-dashed">
            Mobile wallet integration coming soon
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default PaymentMethodTabs;